spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: # 替换为你的 Redis 密码
      database: 1
      timeout: 3000
      jedis:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 500
          min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mortise?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: # 替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: mortisePool
      connection-test-query: SELECT 1
  mail:
    host: smtp.ym.163.com
    port: 465
    username: # 替换为你的邮箱账号
    password: # 替换为你的邮箱密码
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  ai:
    openai:
      api-key: # 替换为你的 OpenAI API Key
      base-url: https://api.openai.com/
logging:
  file:
    path: /logs/mortise
  level:
    com:
      rymcu: info
server:
  port: 8080
  servlet:
    context-path: /mortise
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 10240
  max-http-request-header-size: 10240
version: 1.0
resource:
  domain: # 替换为你的域名
