# 微信公众号多账号配置示例
# application.yml 或 application.properties

# 数据库连接和其他配置已经存在，这里只展示微信公众号配置

# 方式一：标准多账号配置（推荐）
wx:
  mp:
    useRedis: false  # 是否使用 Redis 存储 access token
    configs:
      - appId: wx1234567890123456
        secret: your_app_secret_1
        token: your_token_1
        aesKey: your_aes_key_1
        enabled: true
        accountName: "公众号账号1"
      - appId: wx2234567890123456
        secret: your_app_secret_2
        token: your_token_2
        aesKey: your_aes_key_2
        enabled: true
        accountName: "公众号账号2"
    redisConfig:  # 如果 useRedis: true，则需要配置 Redis
      host: localhost
      port: 6379
      timeout: 2000
      password: your_redis_password

# 方式二：单账号配置（兼容模式）
# wx:
#   mp:
#     appId: wx1234567890123456
#     secret: your_app_secret
#     token: your_token
#     aesKey: your_aes_key
#     enabled: true

# 启用微信公众号功能
wechat:
  mp:
    enabled: true

---
# application.properties 格式示例：

# 多账号配置
# wx.mp.useRedis=false
# wx.mp.configs[0].appId=wx1234567890123456
# wx.mp.configs[0].secret=your_app_secret_1
# wx.mp.configs[0].token=your_token_1
# wx.mp.configs[0].aesKey=your_aes_key_1
# wx.mp.configs[0].enabled=true
# wx.mp.configs[0].accountName=公众号账号1
# wx.mp.configs[1].appId=wx2234567890123456
# wx.mp.configs[1].secret=your_app_secret_2
# wx.mp.configs[1].token=your_token_2
# wx.mp.configs[1].aesKey=your_aes_key_2
# wx.mp.configs[1].enabled=true
# wx.mp.configs[1].accountName=公众号账号2

# 启用微信公众号功能
# wechat.mp.enabled=true